version: '3.4'

services:
  api:
    restart: always
    environment:
      - GOPAD_API_LOG_LEVEL=debug
      - GOPAD_API_SERVER_HOST=${GOPAD_API_SERVER_HOST:-http://localhost:8080}
      - GOPAD_API_TOKEN_SECRET=${GOPAD_API_TOKEN_SECRET:-L74nhDNyckVW7bRodrCgP0hz}
      - GOPAD_API_ADMIN_EMAIL=admin@webhippie.de
    ports:
      - ${GOPAD_API_SERVER_PORT:-8080}:8080
