[run]
watch_all = true
watch_dirs = ["cmd", "pkg"]
watch_exts = [".go"]
ignore = [".git", "docs", "storage"]
ignore_files = []
build_delay = 1500
interrupt_timout = 15
graceful_kill = false

init_cmds = [
  ["mkdir", "-p", "storage"],
  ["make", "build"],
  [
    "./bin/gopad-api",
    "--log-level",
    "debug",
    "server",
    "--db-dsn",
    "boltdb://storage/gopad.db"
  ]
]

cmds = [
  ["make", "build"],
  [
    "./bin/gopad-api",
    "--log-level",
    "debug",
    "server",
    "--db-dsn",
    "boltdb://storage/gopad.db"
  ]
]
