# escape=`
FROM microsoft/nanoserver:10.0.14393.1593

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Gopad API" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 8080 8090
VOLUME c:\gopad

ENTRYPOINT ["c:\\gopad-api.exe"]
CMD ["server"]

ENV GOPAD_API_UPLOAD_DSN file://gopad/

COPY bin/gopad-api.exe c:\gopad-api.exe
