version: '3.4'

volumes:
  mariadb:

services:
  api:
    environment:
      - GOPAD_API_DATABASE_DRIVER=mysql
      - GOPAD_API_DATABASE_ADDRESS=db
      - GOPAD_API_DATABASE_PORT=3306
      - GOPAD_API_DATABASE_USERNAME=gopad
      - GOPAD_API_DATABASE_PASSWORD=gopad
      - GOPAD_API_DATABASE_NAME=gopad
    depends_on:
      - db

  db:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=gopad
      - MARIADB_PASSWORD=gopad
      - MARIADB_DATABASE=gopad
    volumes:
      - mariadb:/var/lib/mysql
