version: '3.4'

volumes:
  postgres:

services:
  api:
    environment:
      - GOPAD_API_DATABASE_DRIVER=postgres
      - GOPAD_API_DATABASE_ADDRESS=db
      - GOPAD_API_DATABASE_PORT=5432
      - GOPAD_API_DATABASE_USERNAME=gopad
      - GOPAD_API_DATABASE_PASSWORD=gopad
      - GOPAD_API_DATABASE_NAME=gopad
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=gopad
      - POSTGRES_PASSWORD=gopad
      - POSTGRES_DB=gopad
    volumes:
      - postgres:/var/lib/postgresql
