version: '3.4'

volumes:
  postgres:

services:
  api:
    environment:
      - GOPAD_API_DATABASE_DSN=postgres://gopad:gopad@db:5432/gopad
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=gopad
      - POSTGRES_PASSWORD=gopad
      - POSTGRES_DB=gopad
    volumes:
      - postgres:/var/lib/postgresql
