apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "gopad-api.fullname" . }}-providers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopad-api.labels" . | nindent 4 }}

data:
  config.yaml: |
    providers:
      {{- toYaml .Values.auth.providers | nindent 6 }}
