{{- if and .Values.config.admin.create (not .Values.config.admin.existingSecret) }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gopad-api.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopad-api.labels" . | nindent 4 }}

type: Opaque
data:
  {{- $secretName := printf "%s-admin" (include "gopad-api.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $passwordValue := (get $secretData .Values.config.admin.passwordKey) | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.config.admin.usernameKey }}: {{ .Values.config.admin.username | b64enc }}
  {{ .Values.config.admin.passwordKey }}: {{ if .Values.config.admin.password }}{{ .Values.config.admin.password | b64enc }}{{ else }}{{ $passwordValue }}{{ end }}
  {{ .Values.config.admin.emailKey }}: {{ .Values.config.admin.email | b64enc }}
{{- end }}
