{{- if not .Values.config.token.existingSecret }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gopad-api.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopad-api.labels" . | nindent 4 }}

type: Opaque
data:
  {{- $secretName := printf "%s-token" (include "gopad-api.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretValue := (get $secretData .Values.config.token.secretKey) | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.config.token.secretKey }}: {{ $secretValue }}
{{- end }}
