{{- if and .Values.config.scim.enabled (not .Values.config.scim.existingSecret) }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gopad-api.fullname" . }}-scim
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopad-api.labels" . | nindent 4 }}

type: Opaque
data:
  {{- $secretName := printf "%s-scim" (include "gopad-api.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $tokenValue := (get $secretData .Values.config.scim.tokenKey) | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.config.scim.tokenKey }}: {{ if .Values.config.scim.token }}{{ .Values.config.scim.token | b64enc }}{{ else }}{{ $tokenValue }}{{ end }}
{{- end }}
