{{- if and (not .Values.config.database.existingSecret) (ne .Values.config.database.driver "sqlite3") }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "gopad-api.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopad-api.labels" . | nindent 4 }}

type: Opaque
data:
  {{- $secretName := printf "%s-database" (include "gopad-api.fullname" .) }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $passwordValue := (get $secretData .Values.config.database.passwordKey) | default "" }}
  {{ .Values.config.database.passwordKey }}: {{ if .Values.config.database.password }}{{ .Values.config.database.password | b64enc }}{{ else }}{{ $passwordValue }}{{ end }}
{{- end }}
