apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "gopad-api.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gopad-api.server.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.server.replicas }}
  revisionHistoryLimit: 3
  {{- if .Values.updateStrategy }}

  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "gopad-api.server.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "gopad-api.server.labels" . | nindent 8 }}
      annotations:
        {{- if and (not .Values.config.database.existingSecret) (ne .Values.config.database.driver "sqlite3") }}
        checksum/secret-database: {{ (include (print $.Template.BasePath "/secret-database.yaml") . | fromYaml).data | toYaml | sha256sum }}
        {{- end }}
        {{- if and (not .Values.config.upload.existingSecret) (eq .Values.config.database.driver "s3") }}
        checksum/secret-upload: {{ (include (print $.Template.BasePath "/secret-upload.yaml") . | fromYaml).data | toYaml | sha256sum }}
        {{- end }}
        {{- if not .Values.config.token.existingSecret }}
        checksum/secret-token: {{ (include (print $.Template.BasePath "/secret-token.yaml") . | fromYaml).data | toYaml | sha256sum }}
        {{- end }}
        {{- if and (not .Values.config.admin.existingSecret) (.Values.config.admin.create) }}
        checksum/secret-admin: {{ (include (print $.Template.BasePath "/secret-admin.yaml") . | fromYaml).data | toYaml | sha256sum }}
        {{- end }}
        {{- if and (not .Values.config.scim.existingSecret) (.Values.config.scim.enabled) }}
        checksum/secret-scim: {{ (include (print $.Template.BasePath "/secret-scim.yaml") . | fromYaml).data | toYaml | sha256sum }}
        {{- end }}
        {{- if .Values.annotations }}
        {{- toYaml .Values.annotations | nindent 8 }}
        {{- end }}
        {{- if .Values.server.podAnnotations }}
        {{- toYaml .Values.server.podAnnotations | nindent 8 }}
        {{- end }}

    spec:
      serviceAccountName: {{ include "gopad-api.serviceAccountName" . }}
      {{- if .Values.pullSecrets }}

      imagePullSecrets:
      {{- range .Values.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.server.securityContext }}

      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.server.extraInitContainers }}

      initContainers:
        {{- toYaml .Values.server.extraInitContainers | nindent 8 }}
      {{- end }}

      containers:
        - name: gopad-api-server
          image: {{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- with .Values.server.podSecurityContext }}

          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            {{- include "gopad-api.server.environment" . | nindent 12 }}

          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.server.service.port }}
            - name: metrics
              protocol: TCP
              containerPort: {{ .Values.server.metrics.internalPort }}
          {{- if .Values.server.resources }}

          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          {{- end }}

          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: providers
              mountPath: /etc/gopad-api/auth
              readOnly: true
          {{- if .Values.server.extraVolumeMounts }}
            {{- toYaml .Values.server.extraVolumeMounts | nindent 12 }}
          {{- end }}
        {{- if .Values.server.extraSidecarContainers }}

        {{- toYaml .Values.server.extraSidecarContainers | nindent 8 }}
        {{- end }}

      volumes:
        - name: providers
          configMap:
            name: {{ include "gopad-api.fullname" . }}-providers
      {{- if .Values.server.extraVolumes }}
        {{- toYaml .Values.server.extraVolumes | nindent 8 }}
      {{- end }}
