// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AttachGroupToUserData, AttachGroupToUserErrors, AttachGroupToUserResponses, AttachUserToGroupData, AttachUserToGroupErrors, AttachUserToGroupResponses, CallbackProviderData, CallbackProviderErrors, CreateGroupData, CreateGroupErrors, CreateGroupResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteGroupData, DeleteGroupErrors, DeleteGroupFromUserData, DeleteGroupFromUserErrors, DeleteGroupFromUserResponses, DeleteGroupResponses, DeleteUserData, DeleteUserErrors, DeleteUserFromGroupData, DeleteUserFromGroupErrors, DeleteUserFromGroupResponses, DeleteUserResponses, ListGroupsData, ListGroupsErrors, ListGroupsResponses, ListGroupUsersData, ListGroupUsersErrors, ListGroupUsersResponses, ListProvidersData, ListProvidersResponses, ListUserGroupsData, ListUserGroupsErrors, ListUserGroupsResponses, ListUsersData, ListUsersErrors, ListUsersResponses, LoginAuthData, LoginAuthErrors, LoginAuthResponses, PermitGroupUserData, PermitGroupUserErrors, PermitGroupUserResponses, PermitUserGroupData, PermitUserGroupErrors, PermitUserGroupResponses, RedirectAuthData, RedirectAuthErrors, RedirectAuthResponses, RefreshAuthData, RefreshAuthErrors, RefreshAuthResponses, RequestProviderData, RequestProviderErrors, ShowGroupData, ShowGroupErrors, ShowGroupResponses, ShowProfileData, ShowProfileErrors, ShowProfileResponses, ShowUserData, ShowUserErrors, ShowUserResponses, TokenProfileData, TokenProfileErrors, TokenProfileResponses, UpdateGroupData, UpdateGroupErrors, UpdateGroupResponses, UpdateProfileData, UpdateProfileErrors, UpdateProfileResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses, VerifyAuthData, VerifyAuthErrors, VerifyAuthResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Request the redirect to defined provider
 */
export const requestProvider = <ThrowOnError extends boolean = false>(options: Options<RequestProviderData, ThrowOnError>) => (options.client ?? client).get<unknown, RequestProviderErrors, ThrowOnError>({ url: '/auth/{provider}/request', ...options });

/**
 * Callback to parse the defined provider
 */
export const callbackProvider = <ThrowOnError extends boolean = false>(options: Options<CallbackProviderData, ThrowOnError>) => (options.client ?? client).get<unknown, CallbackProviderErrors, ThrowOnError>({ url: '/auth/{provider}/callback', ...options });

/**
 * Fetch the available auth providers
 */
export const listProviders = <ThrowOnError extends boolean = false>(options?: Options<ListProvidersData, ThrowOnError>) => (options?.client ?? client).get<ListProvidersResponses, unknown, ThrowOnError>({ url: '/auth/providers', ...options });

/**
 * Retrieve real token after redirect
 */
export const redirectAuth = <ThrowOnError extends boolean = false>(options: Options<RedirectAuthData, ThrowOnError>) => (options.client ?? client).post<RedirectAuthResponses, RedirectAuthErrors, ThrowOnError>({
    url: '/auth/redirect',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authenticate an user by credentials
 */
export const loginAuth = <ThrowOnError extends boolean = false>(options: Options<LoginAuthData, ThrowOnError>) => (options.client ?? client).post<LoginAuthResponses, LoginAuthErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Refresh an auth token before it expires
 */
export const refreshAuth = <ThrowOnError extends boolean = false>(options?: Options<RefreshAuthData, ThrowOnError>) => (options?.client ?? client).get<RefreshAuthResponses, RefreshAuthErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/auth/refresh',
    ...options
});

/**
 * Verify validity for an authentication token
 */
export const verifyAuth = <ThrowOnError extends boolean = false>(options?: Options<VerifyAuthData, ThrowOnError>) => (options?.client ?? client).get<VerifyAuthResponses, VerifyAuthErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/auth/verify',
    ...options
});

/**
 * Retrieve an unlimited auth token
 */
export const tokenProfile = <ThrowOnError extends boolean = false>(options?: Options<TokenProfileData, ThrowOnError>) => (options?.client ?? client).get<TokenProfileResponses, TokenProfileErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/profile/token',
    ...options
});

/**
 * Fetch profile details of the personal account
 */
export const showProfile = <ThrowOnError extends boolean = false>(options?: Options<ShowProfileData, ThrowOnError>) => (options?.client ?? client).get<ShowProfileResponses, ShowProfileErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/profile/self',
    ...options
});

/**
 * Update your own profile information
 */
export const updateProfile = <ThrowOnError extends boolean = false>(options: Options<UpdateProfileData, ThrowOnError>) => (options.client ?? client).put<UpdateProfileResponses, UpdateProfileErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/profile/self',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch all available groups
 */
export const listGroups = <ThrowOnError extends boolean = false>(options?: Options<ListGroupsData, ThrowOnError>) => (options?.client ?? client).get<ListGroupsResponses, ListGroupsErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups',
    ...options
});

/**
 * Create a new group
 */
export const createGroup = <ThrowOnError extends boolean = false>(options: Options<CreateGroupData, ThrowOnError>) => (options.client ?? client).post<CreateGroupResponses, CreateGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a specific group
 */
export const deleteGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteGroupData, ThrowOnError>) => (options.client ?? client).delete<DeleteGroupResponses, DeleteGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}',
    ...options
});

/**
 * Fetch a specific group
 */
export const showGroup = <ThrowOnError extends boolean = false>(options: Options<ShowGroupData, ThrowOnError>) => (options.client ?? client).get<ShowGroupResponses, ShowGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}',
    ...options
});

/**
 * Update a specific group
 */
export const updateGroup = <ThrowOnError extends boolean = false>(options: Options<UpdateGroupData, ThrowOnError>) => (options.client ?? client).put<UpdateGroupResponses, UpdateGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unlink a user from group
 */
export const deleteGroupFromUser = <ThrowOnError extends boolean = false>(options: Options<DeleteGroupFromUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteGroupFromUserResponses, DeleteGroupFromUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch all users attached to group
 */
export const listGroupUsers = <ThrowOnError extends boolean = false>(options: Options<ListGroupUsersData, ThrowOnError>) => (options.client ?? client).get<ListGroupUsersResponses, ListGroupUsersErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}/users',
    ...options
});

/**
 * Attach a user to group
 */
export const attachGroupToUser = <ThrowOnError extends boolean = false>(options: Options<AttachGroupToUserData, ThrowOnError>) => (options.client ?? client).post<AttachGroupToUserResponses, AttachGroupToUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update user perms for group
 */
export const permitGroupUser = <ThrowOnError extends boolean = false>(options: Options<PermitGroupUserData, ThrowOnError>) => (options.client ?? client).put<PermitGroupUserResponses, PermitGroupUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/groups/{group_id}/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch all available users
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>) => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users',
    ...options
});

/**
 * Create a new user
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a specific user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}',
    ...options
});

/**
 * Fetch a specific user
 */
export const showUser = <ThrowOnError extends boolean = false>(options: Options<ShowUserData, ThrowOnError>) => (options.client ?? client).get<ShowUserResponses, ShowUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}',
    ...options
});

/**
 * Update a specific user
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).put<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unlink a group from user
 */
export const deleteUserFromGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteUserFromGroupData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserFromGroupResponses, DeleteUserFromGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}/groups',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fetch all groups attached to user
 */
export const listUserGroups = <ThrowOnError extends boolean = false>(options: Options<ListUserGroupsData, ThrowOnError>) => (options.client ?? client).get<ListUserGroupsResponses, ListUserGroupsErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}/groups',
    ...options
});

/**
 * Attach a group to user
 */
export const attachUserToGroup = <ThrowOnError extends boolean = false>(options: Options<AttachUserToGroupData, ThrowOnError>) => (options.client ?? client).post<AttachUserToGroupResponses, AttachUserToGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}/groups',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update group perms for user
 */
export const permitUserGroup = <ThrowOnError extends boolean = false>(options: Options<PermitUserGroupData, ThrowOnError>) => (options.client ?? client).put<PermitUserGroupResponses, PermitUserGroupErrors, ThrowOnError>({
    security: [
        { name: 'X-API-Key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
        { scheme: 'basic', type: 'http' }
    ],
    url: '/users/{user_id}/groups',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
