// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gopad/gopad-api/pkg/api/v1/models"
)

// UserShowOKCode is the HTTP code returned for type UserShowOK
const UserShowOKCode int = 200

/*UserShowOK The fetched user details

swagger:response userShowOK
*/
type UserShowOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUserShowOK creates UserShowOK with default headers values
func NewUserShowOK() *UserShowOK {

	return &UserShowOK{}
}

// WithPayload adds the payload to the user show o k response
func (o *UserShowOK) WithPayload(payload *models.User) *UserShowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user show o k response
func (o *UserShowOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserShowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UserShowForbiddenCode is the HTTP code returned for type UserShowForbidden
const UserShowForbiddenCode int = 403

/*UserShowForbidden User is not authorized

swagger:response userShowForbidden
*/
type UserShowForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewUserShowForbidden creates UserShowForbidden with default headers values
func NewUserShowForbidden() *UserShowForbidden {

	return &UserShowForbidden{}
}

// WithPayload adds the payload to the user show forbidden response
func (o *UserShowForbidden) WithPayload(payload *models.GeneralError) *UserShowForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user show forbidden response
func (o *UserShowForbidden) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserShowForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UserShowDefault Some error unrelated to the handler

swagger:response userShowDefault
*/
type UserShowDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewUserShowDefault creates UserShowDefault with default headers values
func NewUserShowDefault(code int) *UserShowDefault {
	if code <= 0 {
		code = 500
	}

	return &UserShowDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user show default response
func (o *UserShowDefault) WithStatusCode(code int) *UserShowDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user show default response
func (o *UserShowDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user show default response
func (o *UserShowDefault) WithPayload(payload *models.GeneralError) *UserShowDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user show default response
func (o *UserShowDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserShowDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
