FROM i386/alpine:3.20 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 8000 8080
VOLUME ["/var/lib/gopad"]
ENTRYPOINT ["/usr/bin/gopad-api"]
CMD ["server"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

ENV GOPAD_API_DATABASE_DSN sqlite:///var/lib/gopad/database.sqlite3
ENV GOPAD_API_UPLOAD_DSN file:///var/lib/gopad/uploads

COPY bin/gopad-api /usr/bin/gopad-api
