# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Gopad API" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 8080 8090
VOLUME c:\gopad

ENV GOPAD_API_DB_DSN boltdb:///gopad/database.db
ENV GOPAD_API_UPLOAD_DSN file:///gopad/uploads

ENTRYPOINT ["c:\\gopad-api.exe"]
CMD ["server"]

COPY bin/gopad-api.exe c:\gopad-api.exe
