// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gopad/gopad-api/pkg/api/v1/models"
)

// ProfileUpdateOKCode is the HTTP code returned for type ProfileUpdateOK
const ProfileUpdateOKCode int = 200

/*ProfileUpdateOK The updated profile data

swagger:response profileUpdateOK
*/
type ProfileUpdateOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewProfileUpdateOK creates ProfileUpdateOK with default headers values
func NewProfileUpdateOK() *ProfileUpdateOK {

	return &ProfileUpdateOK{}
}

// WithPayload adds the payload to the profile update o k response
func (o *ProfileUpdateOK) WithPayload(payload *models.Profile) *ProfileUpdateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the profile update o k response
func (o *ProfileUpdateOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProfileUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProfileUpdateForbiddenCode is the HTTP code returned for type ProfileUpdateForbidden
const ProfileUpdateForbiddenCode int = 403

/*ProfileUpdateForbidden User is not authorized

swagger:response profileUpdateForbidden
*/
type ProfileUpdateForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewProfileUpdateForbidden creates ProfileUpdateForbidden with default headers values
func NewProfileUpdateForbidden() *ProfileUpdateForbidden {

	return &ProfileUpdateForbidden{}
}

// WithPayload adds the payload to the profile update forbidden response
func (o *ProfileUpdateForbidden) WithPayload(payload *models.GeneralError) *ProfileUpdateForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the profile update forbidden response
func (o *ProfileUpdateForbidden) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProfileUpdateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProfileUpdatePreconditionFailedCode is the HTTP code returned for type ProfileUpdatePreconditionFailed
const ProfileUpdatePreconditionFailedCode int = 412

/*ProfileUpdatePreconditionFailed Failed to parse request body

swagger:response profileUpdatePreconditionFailed
*/
type ProfileUpdatePreconditionFailed struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewProfileUpdatePreconditionFailed creates ProfileUpdatePreconditionFailed with default headers values
func NewProfileUpdatePreconditionFailed() *ProfileUpdatePreconditionFailed {

	return &ProfileUpdatePreconditionFailed{}
}

// WithPayload adds the payload to the profile update precondition failed response
func (o *ProfileUpdatePreconditionFailed) WithPayload(payload *models.GeneralError) *ProfileUpdatePreconditionFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the profile update precondition failed response
func (o *ProfileUpdatePreconditionFailed) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProfileUpdatePreconditionFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(412)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ProfileUpdateUnprocessableEntityCode is the HTTP code returned for type ProfileUpdateUnprocessableEntity
const ProfileUpdateUnprocessableEntityCode int = 422

/*ProfileUpdateUnprocessableEntity Failed to validate request

swagger:response profileUpdateUnprocessableEntity
*/
type ProfileUpdateUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ValidationError `json:"body,omitempty"`
}

// NewProfileUpdateUnprocessableEntity creates ProfileUpdateUnprocessableEntity with default headers values
func NewProfileUpdateUnprocessableEntity() *ProfileUpdateUnprocessableEntity {

	return &ProfileUpdateUnprocessableEntity{}
}

// WithPayload adds the payload to the profile update unprocessable entity response
func (o *ProfileUpdateUnprocessableEntity) WithPayload(payload *models.ValidationError) *ProfileUpdateUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the profile update unprocessable entity response
func (o *ProfileUpdateUnprocessableEntity) SetPayload(payload *models.ValidationError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProfileUpdateUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ProfileUpdateDefault Some error unrelated to the handler

swagger:response profileUpdateDefault
*/
type ProfileUpdateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewProfileUpdateDefault creates ProfileUpdateDefault with default headers values
func NewProfileUpdateDefault(code int) *ProfileUpdateDefault {
	if code <= 0 {
		code = 500
	}

	return &ProfileUpdateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the profile update default response
func (o *ProfileUpdateDefault) WithStatusCode(code int) *ProfileUpdateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the profile update default response
func (o *ProfileUpdateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the profile update default response
func (o *ProfileUpdateDefault) WithPayload(payload *models.GeneralError) *ProfileUpdateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the profile update default response
func (o *ProfileUpdateDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProfileUpdateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
