---
server:
  addr: 0.0.0.0:8080
  host: http://localhost:8080
  root: "/"
  cert: ~
  key: ~
  templates: ~
  docs: true

metrics:
  addr: 0.0.0.0:8000
  token: ~
  pprof: false

logs:
  level: info
  pretty: true
  color: true

auth:
  config: ~

database:
  driver: sqlite3
  address: ~
  port: ~
  username: ~
  password: ~
  name: storage/gopad.sqlite3
  options: {}

upload:
  driver: file
  endpoint: ~
  path: storage/uploads/
  access: ~
  secret: ~
  bucket: ~
  region: us-east-1
  perms: "0755"

token:
  secret: TxHrYxMAg01rBeEWrHn1BjOP
  expire: 1h0m0s

scim:
  enabled: false
  token: ~

admin:
  create: true
  username: admin
  password: p455w0rd
  email: admin@localhost
  users:
    - username1
    - username2
    - username3

...
