// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gopad/gopad-api/pkg/api/v1/models"
)

// AuthLoginOKCode is the HTTP code returned for type AuthLoginOK
const AuthLoginOKCode int = 200

/*AuthLoginOK A generated token with expire

swagger:response authLoginOK
*/
type AuthLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthToken `json:"body,omitempty"`
}

// NewAuthLoginOK creates AuthLoginOK with default headers values
func NewAuthLoginOK() *AuthLoginOK {

	return &AuthLoginOK{}
}

// WithPayload adds the payload to the auth login o k response
func (o *AuthLoginOK) WithPayload(payload *models.AuthToken) *AuthLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth login o k response
func (o *AuthLoginOK) SetPayload(payload *models.AuthToken) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AuthLoginUnauthorizedCode is the HTTP code returned for type AuthLoginUnauthorized
const AuthLoginUnauthorizedCode int = 401

/*AuthLoginUnauthorized Unauthorized if wrong credentials

swagger:response authLoginUnauthorized
*/
type AuthLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewAuthLoginUnauthorized creates AuthLoginUnauthorized with default headers values
func NewAuthLoginUnauthorized() *AuthLoginUnauthorized {

	return &AuthLoginUnauthorized{}
}

// WithPayload adds the payload to the auth login unauthorized response
func (o *AuthLoginUnauthorized) WithPayload(payload *models.GeneralError) *AuthLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth login unauthorized response
func (o *AuthLoginUnauthorized) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AuthLoginDefault Some error unrelated to the handler

swagger:response authLoginDefault
*/
type AuthLoginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewAuthLoginDefault creates AuthLoginDefault with default headers values
func NewAuthLoginDefault(code int) *AuthLoginDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthLoginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auth login default response
func (o *AuthLoginDefault) WithStatusCode(code int) *AuthLoginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auth login default response
func (o *AuthLoginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the auth login default response
func (o *AuthLoginDefault) WithPayload(payload *models.GeneralError) *AuthLoginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth login default response
func (o *AuthLoginDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthLoginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
