// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/gopad/gopad-api/pkg/api/v1/models"
)

// AuthVerifyOKCode is the HTTP code returned for type AuthVerifyOK
const AuthVerifyOKCode int = 200

/*AuthVerifyOK Meta data of the provided token

swagger:response authVerifyOK
*/
type AuthVerifyOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthVerify `json:"body,omitempty"`
}

// NewAuthVerifyOK creates AuthVerifyOK with default headers values
func NewAuthVerifyOK() *AuthVerifyOK {

	return &AuthVerifyOK{}
}

// WithPayload adds the payload to the auth verify o k response
func (o *AuthVerifyOK) WithPayload(payload *models.AuthVerify) *AuthVerifyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth verify o k response
func (o *AuthVerifyOK) SetPayload(payload *models.AuthVerify) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthVerifyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AuthVerifyUnauthorizedCode is the HTTP code returned for type AuthVerifyUnauthorized
const AuthVerifyUnauthorizedCode int = 401

/*AuthVerifyUnauthorized Unauthorized if token is invalid

swagger:response authVerifyUnauthorized
*/
type AuthVerifyUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewAuthVerifyUnauthorized creates AuthVerifyUnauthorized with default headers values
func NewAuthVerifyUnauthorized() *AuthVerifyUnauthorized {

	return &AuthVerifyUnauthorized{}
}

// WithPayload adds the payload to the auth verify unauthorized response
func (o *AuthVerifyUnauthorized) WithPayload(payload *models.GeneralError) *AuthVerifyUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth verify unauthorized response
func (o *AuthVerifyUnauthorized) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthVerifyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AuthVerifyDefault Some error unrelated to the handler

swagger:response authVerifyDefault
*/
type AuthVerifyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewAuthVerifyDefault creates AuthVerifyDefault with default headers values
func NewAuthVerifyDefault(code int) *AuthVerifyDefault {
	if code <= 0 {
		code = 500
	}

	return &AuthVerifyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auth verify default response
func (o *AuthVerifyDefault) WithStatusCode(code int) *AuthVerifyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auth verify default response
func (o *AuthVerifyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the auth verify default response
func (o *AuthVerifyDefault) WithPayload(payload *models.GeneralError) *AuthVerifyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth verify default response
func (o *AuthVerifyDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthVerifyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
