// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/gopad/gopad-api/pkg/api/v1/models"
)

// NewAppendTeamToUserParams creates a new AppendTeamToUserParams object
//
// There are no default values defined in the spec.
func NewAppendTeamToUserParams() AppendTeamToUserParams {

	return AppendTeamToUserParams{}
}

// AppendTeamToUserParams contains all the bound params for the append team to user operation
// typically these are obtained from a http.Request
//
// swagger:parameters AppendTeamToUser
type AppendTeamToUserParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A team UUID or slug
	  Required: true
	  In: path
	*/
	TeamID string
	/*The team user data to assign
	  Required: true
	  In: body
	*/
	TeamUser *models.TeamUserParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAppendTeamToUserParams() beforehand.
func (o *AppendTeamToUserParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTeamID, rhkTeamID, _ := route.Params.GetOK("team_id")
	if err := o.bindTeamID(rTeamID, rhkTeamID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.TeamUserParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("teamUser", "body", ""))
			} else {
				res = append(res, errors.NewParseError("teamUser", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TeamUser = &body
			}
		}
	} else {
		res = append(res, errors.Required("teamUser", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTeamID binds and validates parameter TeamID from path.
func (o *AppendTeamToUserParams) bindTeamID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.TeamID = raw

	return nil
}
