// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gopad/gopad-api/pkg/api/v1/models"
)

// ListTeamsOKCode is the HTTP code returned for type ListTeamsOK
const ListTeamsOKCode int = 200

/*
ListTeamsOK A collection of teams

swagger:response listTeamsOK
*/
type ListTeamsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Team `json:"body,omitempty"`
}

// NewListTeamsOK creates ListTeamsOK with default headers values
func NewListTeamsOK() *ListTeamsOK {

	return &ListTeamsOK{}
}

// WithPayload adds the payload to the list teams o k response
func (o *ListTeamsOK) WithPayload(payload []*models.Team) *ListTeamsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list teams o k response
func (o *ListTeamsOK) SetPayload(payload []*models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTeamsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Team, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListTeamsForbiddenCode is the HTTP code returned for type ListTeamsForbidden
const ListTeamsForbiddenCode int = 403

/*
ListTeamsForbidden User is not authorized

swagger:response listTeamsForbidden
*/
type ListTeamsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewListTeamsForbidden creates ListTeamsForbidden with default headers values
func NewListTeamsForbidden() *ListTeamsForbidden {

	return &ListTeamsForbidden{}
}

// WithPayload adds the payload to the list teams forbidden response
func (o *ListTeamsForbidden) WithPayload(payload *models.GeneralError) *ListTeamsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list teams forbidden response
func (o *ListTeamsForbidden) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTeamsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ListTeamsDefault Some error unrelated to the handler

swagger:response listTeamsDefault
*/
type ListTeamsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewListTeamsDefault creates ListTeamsDefault with default headers values
func NewListTeamsDefault(code int) *ListTeamsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListTeamsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list teams default response
func (o *ListTeamsDefault) WithStatusCode(code int) *ListTeamsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list teams default response
func (o *ListTeamsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list teams default response
func (o *ListTeamsDefault) WithPayload(payload *models.GeneralError) *ListTeamsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list teams default response
func (o *ListTeamsDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTeamsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
