// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PermitTeamUserHandlerFunc turns a function with the right signature into a permit team user handler
type PermitTeamUserHandlerFunc func(PermitTeamUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PermitTeamUserHandlerFunc) Handle(params PermitTeamUserParams) middleware.Responder {
	return fn(params)
}

// PermitTeamUserHandler interface for that can handle valid permit team user params
type PermitTeamUserHandler interface {
	Handle(PermitTeamUserParams) middleware.Responder
}

// NewPermitTeamUser creates a new http.Handler for the permit team user operation
func NewPermitTeamUser(ctx *middleware.Context, handler PermitTeamUserHandler) *PermitTeamUser {
	return &PermitTeamUser{Context: ctx, Handler: handler}
}

/*PermitTeamUser swagger:route PUT /teams/{teamID}/users team permitTeamUser

Update user perms for team

*/
type PermitTeamUser struct {
	Context *middleware.Context
	Handler PermitTeamUserHandler
}

func (o *PermitTeamUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPermitTeamUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
