// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TeamShowHandlerFunc turns a function with the right signature into a team show handler
type TeamShowHandlerFunc func(TeamShowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TeamShowHandlerFunc) Handle(params TeamShowParams) middleware.Responder {
	return fn(params)
}

// TeamShowHandler interface for that can handle valid team show params
type TeamShowHandler interface {
	Handle(TeamShowParams) middleware.Responder
}

// NewTeamShow creates a new http.Handler for the team show operation
func NewTeamShow(ctx *middleware.Context, handler TeamShowHandler) *TeamShow {
	return &TeamShow{Context: ctx, Handler: handler}
}

/*TeamShow swagger:route GET /teams/{teamID} team teamShow

Fetch a specific team

*/
type TeamShow struct {
	Context *middleware.Context
	Handler TeamShowHandler
}

func (o *TeamShow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTeamShowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
