// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TeamIndexHandlerFunc turns a function with the right signature into a team index handler
type TeamIndexHandlerFunc func(TeamIndexParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TeamIndexHandlerFunc) Handle(params TeamIndexParams) middleware.Responder {
	return fn(params)
}

// TeamIndexHandler interface for that can handle valid team index params
type TeamIndexHandler interface {
	Handle(TeamIndexParams) middleware.Responder
}

// NewTeamIndex creates a new http.Handler for the team index operation
func NewTeamIndex(ctx *middleware.Context, handler TeamIndexHandler) *TeamIndex {
	return &TeamIndex{Context: ctx, Handler: handler}
}

/*TeamIndex swagger:route GET /teams team teamIndex

Fetch all available teams

*/
type TeamIndex struct {
	Context *middleware.Context
	Handler TeamIndexHandler
}

func (o *TeamIndex) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTeamIndexParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
