---
name: docker

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            gopad/gopad-api
            quay.io/gopad/gopad-api
            ghcr.io/gopad/gopad-api
          labels: |
            org.opencontainers.image.vendor=Gopad
            maintainer=Thomas Boerger <thomas@webhippie.de>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Ghcr login
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: cmd/gopad-api/Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  readme:
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Hub readme
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          target: gopad/gopad-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: "Gopad: API"
          readme: README.md

      - name: Quay readme
        uses: actionhippie/pushrm@v1
        with:
          provider: quay
          target: quay.io/gopad/gopad-api
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
