---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: openapi

"on":
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Install tools
        uses: jdx/mise-action@v5

      - name: Upload spec
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        run: |
          s5cmd cp openapi/v1.yaml s3://dl.gopad.eu/openapi/$(yq -r .info.version openapi/v1.yaml).yaml

...
