---
name: protobuf

"on":
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  protobuf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Setup buf
        id: buf
        uses: bufbuild/buf-setup-action@v1.30.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linting
        id: linting
        uses: bufbuild/buf-lint-action@v1.1.1
        with:
          input: proto/

      - name: Run breaking
        id: breaking
        uses: bufbuild/buf-breaking-action@v1.1.4
        with:
          input: proto/
          against: https://github.com/${{ github.repository }}.git#branch=master

      - name: Buf publish
        id: publish
        uses: bufbuild/buf-push-action@v1.2.0
        if: github.event_name != 'pull_request'
        with:
          input: proto/
          buf_token: ${{ secrets.BUF_TOKEN }}

...
