---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: schema

"on":
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Generate schema
        run: go run ./hack/jsonschema --out dist/schema

      - name: Upload schema
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        run: |
          s5cmd cp dist/schema/ s3://dl.gopad.eu/schema/

...
